file:
  chunk: books.csv

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:~/BookstoreBatchDb;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
